/**
 * @fileoverview Unmonitored regulatory authorities — "Coverage Gaps"
 * These are authorities NOT currently in the reg library's 79 monitored sources.
 * Each entry has a name and a region guess: Global | UK/EU | AMER | APAC | ME/AF
 */

export const ADDITIONAL_AUTHORITIES = [
  { name: 'Abu Dhabi Global Market', region: 'ME/AF' },
  { name: 'Abu Dhabi Office of Data Protection', region: 'ME/AF' },
  { name: 'Access to Cash Review', region: 'UK/EU' },
  { name: 'Administrative Council for Economic Defense - Brazil', region: 'AMER' },
  { name: 'Advertising Regulatory Board', region: 'ME/AF' },
  { name: 'Advertising Standards Authority', region: 'UK/EU' },
  { name: 'Advertising Standards Authority for Ireland', region: 'UK/EU' },
  { name: 'Advertising Standards Authority of Singapore', region: 'APAC' },
  { name: 'Advertising Standards Council of India', region: 'APAC' },
  { name: 'Agence Française Anticorruption', region: 'UK/EU' },
  { name: 'Agencia Espanola Proteccion Datos', region: 'UK/EU' },
  { name: 'Agency Against Corruption', region: 'Global' },
  { name: 'Agency for Digital Italy', region: 'UK/EU' },
  { name: 'Agency for Personal Data Protection', region: 'UK/EU' },
  { name: 'Agency for Protection of Competition', region: 'UK/EU' },
  { name: 'American Bankers Association', region: 'AMER' },
  { name: 'Angola Data Protection Agency', region: 'ME/AF' },
  { name: 'Angola Financial Intelligence Unit', region: 'ME/AF' },
  { name: 'Anti-Money Laundering and Counter-Terrorism Financing Office', region: 'APAC' },
  { name: 'Anti-Money Laundering Authority (AMLA) - EU', region: 'UK/EU' },
  { name: 'Anti-Money Laundering Division (Executive Yuan)', region: 'APAC' },
  { name: 'Antimonopoly Office of the Slovak Republic', region: 'UK/EU' },
  { name: 'Argentina Ministry of Economy', region: 'AMER' },
  { name: 'Argentine Bankers Association', region: 'AMER' },
  { name: 'Armenia Personal Data Protection Agency', region: 'UK/EU' },
  { name: 'Armenia State Commission for the Protection of Economic Competition', region: 'UK/EU' },
  { name: 'ASEAN', region: 'APAC' },
  { name: 'Asia/Pacific Group on Money Laundering (APG)', region: 'APAC' },
  { name: 'Asian Financial Cooperation Association', region: 'APAC' },
  { name: 'Association of Banks in Cambodia', region: 'APAC' },
  { name: 'Association of Banks in Fiji', region: 'APAC' },
  { name: 'Association of Banks of Singapore', region: 'APAC' },
  { name: 'Association of German Banks', region: 'UK/EU' },
  { name: 'Association of Serbian Banks', region: 'UK/EU' },
  { name: 'Australian Banking Association', region: 'APAC' },
  { name: 'Australian Communications and Media Authority', region: 'APAC' },
  { name: 'Australian Competition and Consumer Commission', region: 'APAC' },
  { name: 'Australian Cyber Security Centre', region: 'APAC' },
  { name: 'Australian Department of Home Affairs', region: 'APAC' },
  { name: 'Australian Finance Industry Association Limited', region: 'APAC' },
  { name: 'Australian Financial Complaints Authority', region: 'APAC' },
  { name: 'Australian Human Rights Commission', region: 'APAC' },
  { name: 'Australian Payments Council', region: 'APAC' },
  { name: 'Australian Payments Network', region: 'APAC' },
  { name: 'Australian Prudential Regulation Authority', region: 'APAC' },
  { name: 'Australian Securities and Investments Commission', region: 'APAC' },
  { name: 'Australian Transaction Reports and Analysis Centre', region: 'APAC' },
  { name: 'Australian Treasury', region: 'APAC' },
  { name: 'Austrian Data Protection Council', region: 'UK/EU' },
  { name: 'Austrian Federal Ministry of Finance', region: 'UK/EU' },
  { name: 'Authority for Anti-Money Laundering and Countering the Financing of Terrorism', region: 'UK/EU' },
  { name: 'Autorité de Contrôle Prudentiel et de Résolution', region: 'UK/EU' },
  { name: 'Autorité de la concurrence', region: 'UK/EU' },
  { name: 'Autorité des Marchés Financiers (AMF)', region: 'UK/EU' },
  { name: 'Azerbaijan Competition Authority', region: 'UK/EU' },
  { name: 'Bahrain Government', region: 'ME/AF' },
  { name: 'Banco de España', region: 'UK/EU' },
  { name: 'Banco de la República Colombia', region: 'AMER' },
  { name: 'Banco de México', region: 'AMER' },
  { name: 'Banco de Portugal', region: 'UK/EU' },
  { name: 'Bangko Sentral ng Pilipinas', region: 'APAC' },
  { name: 'Bangladesh Bank', region: 'APAC' },
  { name: 'Bangladesh Financial Intelligence Unit', region: 'APAC' },
  { name: 'Bangladesh Securities and Exchange Commission', region: 'APAC' },
  { name: 'Bank for International Settlements', region: 'Global' },
  { name: 'Bank Indonesia', region: 'APAC' },
  { name: 'Bank Negara Malaysia', region: 'APAC' },
  { name: 'Bank of Albania', region: 'UK/EU' },
  { name: 'Bank of Canada', region: 'AMER' },
  { name: 'Bank of England', region: 'UK/EU' },
  { name: 'Bank of Ghana', region: 'ME/AF' },
  { name: 'Bank of Israel', region: 'ME/AF' },
  { name: 'Bank of Italy', region: 'UK/EU' },
  { name: 'Bank of Japan', region: 'APAC' },
  { name: 'Bank of Korea', region: 'APAC' },
  { name: 'Bank of Mauritius', region: 'ME/AF' },
  { name: 'Bank of Thailand', region: 'APAC' },
  { name: 'Banking Association South Africa', region: 'ME/AF' },
  { name: 'Banque de France', region: 'UK/EU' },
  { name: 'Basel Committee on Banking Supervision', region: 'Global' },
  { name: 'Belgian Competition Authority', region: 'UK/EU' },
  { name: 'Belgian Data Protection Authority', region: 'UK/EU' },
  { name: 'Belgian Financial Intelligence Processing Unit', region: 'UK/EU' },
  { name: 'Bermuda Monetary Authority', region: 'AMER' },
  { name: 'Board of Governors of the Federal Reserve System', region: 'AMER' },
  { name: 'Brazil Superintendence of Private Insurance', region: 'AMER' },
  { name: 'Brazilian Securities and Exchange Commission', region: 'AMER' },
  { name: 'British Columbia Financial Services Authority', region: 'AMER' },
  { name: 'British Columbia Securities Commission', region: 'AMER' },
  { name: 'Bulgarian Commission for Personal Data Protection', region: 'UK/EU' },
  { name: 'Bulgarian Financial Supervision Commission', region: 'UK/EU' },
  { name: 'Bulgarian National Bank', region: 'UK/EU' },
  { name: 'Bundeskartellamt', region: 'UK/EU' },
  { name: 'Cayman Islands Monetary Authority', region: 'AMER' },
  { name: 'Central Bank of Armenia', region: 'UK/EU' },
  { name: 'Central Bank of Bahrain', region: 'ME/AF' },
  { name: 'Central Bank of Bangladesh', region: 'APAC' },
  { name: 'Central Bank of Brazil', region: 'AMER' },
  { name: 'Central Bank of Chile', region: 'AMER' },
  { name: 'Central Bank of Colombia', region: 'AMER' },
  { name: 'Central Bank of Cyprus', region: 'UK/EU' },
  { name: 'Central Bank of Egypt', region: 'ME/AF' },
  { name: 'Central Bank of Ireland', region: 'UK/EU' },
  { name: 'Central Bank of Jordan', region: 'ME/AF' },
  { name: 'Central Bank of Kenya', region: 'ME/AF' },
  { name: 'Central Bank of Luxembourg', region: 'UK/EU' },
  { name: 'Central Bank of Malta', region: 'UK/EU' },
  { name: 'Central Bank of Montenegro', region: 'UK/EU' },
  { name: 'Central Bank of Nigeria', region: 'ME/AF' },
  { name: 'Central Bank of Oman', region: 'ME/AF' },
  { name: 'Central Bank of Sri Lanka', region: 'APAC' },
  { name: 'Central Bank of Tanzania', region: 'ME/AF' },
  { name: 'Central Bank of the Republic of Turkey', region: 'UK/EU' },
  { name: 'Central Bank of the UAE', region: 'ME/AF' },
  { name: 'Central Bank of Uruguay', region: 'AMER' },
  { name: 'Central Bank of Uzbekistan', region: 'APAC' },
  { name: 'Chilean Financial Market Commission (CMF)', region: 'AMER' },
  { name: 'China Banking and Insurance Regulatory Commission', region: 'APAC' },
  { name: 'China Securities Regulatory Commission', region: 'APAC' },
  { name: 'China State Administration for Market Regulation', region: 'APAC' },
  { name: 'Colombian Financial Information and Analysis Unit', region: 'AMER' },
  { name: 'Commodity Futures Trading Commission', region: 'AMER' },
  { name: 'Competition and Consumer Commission of Singapore', region: 'APAC' },
  { name: 'Competition Authority of Kenya', region: 'ME/AF' },
  { name: 'Competition Bureau Canada', region: 'AMER' },
  { name: 'Competition Commission of India', region: 'APAC' },
  { name: 'Competition Commission of South Africa', region: 'ME/AF' },
  { name: 'Consumer Financial Protection Bureau', region: 'AMER' },
  { name: 'Croatian Financial Services Supervision Agency', region: 'UK/EU' },
  { name: 'Croatian National Bank', region: 'UK/EU' },
  { name: 'Cyprus Commission for the Protection of Competition', region: 'UK/EU' },
  { name: 'Cyprus Securities and Exchange Commission', region: 'UK/EU' },
  { name: 'Czech National Bank', region: 'UK/EU' },
  { name: 'Danish Financial Supervisory Authority', region: 'UK/EU' },
  { name: 'Danish Data Protection Agency', region: 'UK/EU' },
  { name: 'Dubai Financial Services Authority', region: 'ME/AF' },
  { name: 'Dubai Virtual Assets Regulatory Authority', region: 'ME/AF' },
  { name: 'Dutch Authority for the Financial Markets', region: 'UK/EU' },
  { name: 'Dutch Central Bank', region: 'UK/EU' },
  { name: 'Dutch Data Protection Authority', region: 'UK/EU' },
  { name: 'Eastern Caribbean Central Bank', region: 'AMER' },
  { name: 'Egyptian Anti-Money Laundering Unit', region: 'ME/AF' },
  { name: 'Egyptian Competition Authority', region: 'ME/AF' },
  { name: 'El Salvador Central Reserve Bank', region: 'AMER' },
  { name: 'Electronic Money Association', region: 'UK/EU' },
  { name: 'Estonian Financial Supervision Authority', region: 'UK/EU' },
  { name: 'European Banking Authority', region: 'UK/EU' },
  { name: 'European Central Bank', region: 'UK/EU' },
  { name: 'European Commission', region: 'UK/EU' },
  { name: 'European Data Protection Board', region: 'UK/EU' },
  { name: 'European Data Protection Supervisor', region: 'UK/EU' },
  { name: 'European Insurance and Occupational Pensions Authority', region: 'UK/EU' },
  { name: 'European Parliament', region: 'UK/EU' },
  { name: 'European Payments Council', region: 'UK/EU' },
  { name: 'European Securities and Markets Authority', region: 'UK/EU' },
  { name: 'European Systemic Risk Board', region: 'UK/EU' },
  { name: 'Europol', region: 'UK/EU' },
  { name: 'Federal Deposit Insurance Corporation', region: 'AMER' },
  { name: 'Federal Financial Institutions Examination Council', region: 'AMER' },
  { name: 'Federal Reserve', region: 'AMER' },
  { name: 'Federal Trade Commission', region: 'AMER' },
  { name: 'Finance Denmark', region: 'UK/EU' },
  { name: 'Finance Finland', region: 'UK/EU' },
  { name: 'Finance Norway', region: 'UK/EU' },
  { name: 'Financial Action Task Force', region: 'Global' },
  { name: 'Financial Crimes Enforcement Network', region: 'AMER' },
  { name: 'Financial Industry Regulatory Authority', region: 'AMER' },
  { name: 'Financial Intelligence Centre - South Africa', region: 'ME/AF' },
  { name: 'Financial Markets Authority - New Zealand', region: 'APAC' },
  { name: 'Financial Reporting Council', region: 'UK/EU' },
  { name: 'Financial Sector Conduct Authority', region: 'ME/AF' },
  { name: 'Financial Services Agency - Japan', region: 'APAC' },
  { name: 'Financial Services and Markets Authority - Belgium', region: 'UK/EU' },
  { name: 'Financial Services Commission - South Korea', region: 'APAC' },
  { name: 'Financial Stability Board', region: 'Global' },
  { name: 'Financial Stability Oversight Council', region: 'AMER' },
  { name: 'Financial Supervisory Authority - Finland', region: 'UK/EU' },
  { name: 'Financial Supervisory Authority - Romania', region: 'UK/EU' },
  { name: 'Financial Supervisory Authority - Sweden', region: 'UK/EU' },
  { name: 'Financial Transactions and Reports Analysis Centre of Canada', region: 'AMER' },
  { name: 'Finnish Competition and Consumer Authority', region: 'UK/EU' },
  { name: 'French Banking Federation', region: 'UK/EU' },
  { name: 'French Competition Authority', region: 'UK/EU' },
  { name: 'G20', region: 'Global' },
  { name: 'German Federal Financial Supervisory Authority', region: 'UK/EU' },
  { name: 'Gibraltar Financial Services Commission', region: 'UK/EU' },
  { name: 'Greek Anti-Money Laundering Authority', region: 'UK/EU' },
  { name: 'Hellenic Capital Market Commission', region: 'UK/EU' },
  { name: 'Hellenic Data Protection Authority', region: 'UK/EU' },
  { name: 'HM Revenue & Customs', region: 'UK/EU' },
  { name: 'HM Treasury', region: 'UK/EU' },
  { name: 'Hong Kong Competition Commission', region: 'APAC' },
  { name: 'Hong Kong Monetary Authority', region: 'APAC' },
  { name: 'Hungarian Competition Authority', region: 'UK/EU' },
  { name: 'Hungarian National Authority for Data Protection', region: 'UK/EU' },
  { name: 'Iceland Financial Supervision Authority', region: 'UK/EU' },
  { name: 'Indonesian Financial Services Authority', region: 'APAC' },
  { name: 'Indonesian Financial Transaction Reports and Analysis Center', region: 'APAC' },
  { name: 'Information Commissioner\'s Office', region: 'UK/EU' },
  { name: 'Insurance Regulatory and Development Authority', region: 'APAC' },
  { name: 'International Finance Corporation', region: 'Global' },
  { name: 'International Monetary Fund', region: 'Global' },
  { name: 'International Organization of Securities Commissions', region: 'Global' },
  { name: 'Irish Competition and Consumer Protection Commission', region: 'UK/EU' },
  { name: 'Irish Data Protection Commission', region: 'UK/EU' },
  { name: 'Irish Department of Finance', region: 'UK/EU' },
  { name: 'Isle of Man Financial Services Authority', region: 'UK/EU' },
  { name: 'Israel Competition Authority', region: 'ME/AF' },
  { name: 'Israel Money Laundering and Terror Financing Prohibition Authority', region: 'ME/AF' },
  { name: 'Israel Privacy Protection Authority', region: 'ME/AF' },
  { name: 'Israel Securities Authority', region: 'ME/AF' },
  { name: 'Italian Competition Authority', region: 'UK/EU' },
  { name: 'Italian Data Protection Authority', region: 'UK/EU' },
  { name: 'Italian National Commission for Companies and the Stock Exchange', region: 'UK/EU' },
  { name: 'Japan Fair Trade Commission', region: 'APAC' },
  { name: 'Japan Financial Intelligence Unit', region: 'APAC' },
  { name: 'Japan Securities Dealers Association', region: 'APAC' },
  { name: 'Japanese Bankers Association', region: 'APAC' },
  { name: 'Joint Money Laundering Steering Group', region: 'UK/EU' },
  { name: 'Jordan Securities Commission', region: 'ME/AF' },
  { name: 'Kazakhstan Agency for Regulation and Development of Financial Market', region: 'APAC' },
  { name: 'Kenya Bankers Association', region: 'ME/AF' },
  { name: 'Kenya Office of the Data Protection Commissioner', region: 'ME/AF' },
  { name: 'Labuan Financial Services Authority', region: 'APAC' },
  { name: 'Latvian Finance and Capital Market Commission', region: 'UK/EU' },
  { name: 'Lithuanian Government', region: 'UK/EU' },
  { name: 'Luxembourg Government', region: 'UK/EU' },
  { name: 'Magyar Nemzeti Bank', region: 'UK/EU' },
  { name: 'Malaysia Securities Commission', region: 'APAC' },
  { name: 'Maldives Monetary Authority', region: 'APAC' },
  { name: 'Malta Financial Services Authority', region: 'UK/EU' },
  { name: 'Mauritius Government', region: 'ME/AF' },
  { name: 'Mexican Federal Competition Commission', region: 'AMER' },
  { name: 'National Bank of Belgium', region: 'UK/EU' },
  { name: 'New Zealand Reserve Bank', region: 'APAC' },
  { name: 'Nigeria Financial Intelligence Unit', region: 'ME/AF' },
  { name: 'Office of the Comptroller of the Currency', region: 'AMER' },
  { name: 'Ontario Securities Commission', region: 'AMER' },
  { name: 'Payment Systems Regulator', region: 'UK/EU' },
  { name: 'People\'s Bank of China', region: 'APAC' },
  { name: 'Philippines Securities and Exchange Commission', region: 'APAC' },
  { name: 'Polish Financial Supervision Authority', region: 'UK/EU' },
  { name: 'Reserve Bank of Australia', region: 'APAC' },
  { name: 'Reserve Bank of India', region: 'APAC' },
  { name: 'Reserve Bank of New Zealand', region: 'APAC' },
  { name: 'Romanian National Bank', region: 'UK/EU' },
  { name: 'Saudi Central Bank (SAMA)', region: 'ME/AF' },
  { name: 'Securities and Exchange Board of India', region: 'APAC' },
  { name: 'Securities and Exchange Commission - Philippines', region: 'APAC' },
  { name: 'Securities and Exchange Commission - US', region: 'AMER' },
  { name: 'Securities Commission Malaysia', region: 'APAC' },
  { name: 'Serious Fraud Office', region: 'UK/EU' },
  { name: 'Singapore Police Force', region: 'APAC' },
  { name: 'South African Reserve Bank', region: 'ME/AF' },
  { name: 'South Korea Financial Services Commission', region: 'APAC' },
  { name: 'Spanish Data Protection Agency', region: 'UK/EU' },
  { name: 'Spanish National Securities Market Commission', region: 'UK/EU' },
  { name: 'Sri Lanka Securities and Exchange Commission', region: 'APAC' },
  { name: 'Swedish Financial Supervisory Authority', region: 'UK/EU' },
  { name: 'Swiss Financial Market Supervisory Authority', region: 'UK/EU' },
  { name: 'Taiwan Financial Supervisory Commission', region: 'APAC' },
  { name: 'Thailand Securities and Exchange Commission', region: 'APAC' },
  { name: 'Turkish Banking Regulation and Supervision Agency', region: 'UK/EU' },
  { name: 'Turkish Capital Markets Board', region: 'UK/EU' },
  { name: 'UAE Securities and Commodities Authority', region: 'ME/AF' },
  { name: 'Uganda Revenue Authority', region: 'ME/AF' },
  { name: 'UK Financial Intelligence Unit', region: 'UK/EU' },
  { name: 'Ukraine National Bank', region: 'UK/EU' },
  { name: 'US Department of Justice', region: 'AMER' },
  { name: 'US Department of the Treasury', region: 'AMER' },
  { name: 'US Office of Foreign Assets Control', region: 'AMER' },
  { name: 'Vietnam State Securities Commission', region: 'APAC' },
  { name: 'World Bank', region: 'Global' },
];
