/**
 * Jurisdiction FS bandings — aligned to Bandings document.
 * 1. High | 2. Medium | 3. Low | '' = unrated/not applicable
 */
export const JURISDICTION_BANDINGS = {
  'Abu Dhabi': '',
  'Alabama': '3. Low',
  'Alaska': '3. Low',
  'Albania': '2. Medium',
  'Alberta': '3. Low',
  'Algeria': '',
  'Andorra': '',
  'Angola': '',
  'Anjouan': '',
  'Antigua and Barbuda': '',
  'Argentina': '1. High',
  'Arizona': '2. Medium',
  'Arkansas': '3. Low',
  'Armenia': '3. Low',
  'Aruba': '',
  'Australia': '1. High',
  'Australian Capital Territory': '',
  'Austria': '1. High',
  'Azerbaijan': '3. Low',
  'Bahamas': '',
  'Bahrain': '3. Low',
  'Bangladesh': '3. Low',
  'Belarus': '3. Low',
  'Belgium': '1. High',
  'Belize': '',
  'Benin': '',
  'Bermuda': '',
  'Bolivia': '',
  'Bosnia and Herzegovina': '',
  'Botswana': '3. Low',
  'Brazil': '1. High',
  'British Columbia': '',
  'Buenos Aires': '',
  'Bulgaria': '1. High',
  'Burkina Faso': '',
  'Burundi': '',
  'Cabo Verde': '',
  'California': '1. High',
  'Cambodia': '3. Low',
  'Cameroon': '',
  'Canada': '1. High',
  'Central African Republic': '',
  'Chile': '1. High',
  'China': '2. Medium',
  'Colombia': '2. Medium',
  'Colorado': '2. Medium',
  'Commonwealth of Northern Mariana Islands': '',
  'Connecticut': '2. Medium',
  'Costa Rica': '2. Medium',
  "Cote d'Ivoire": '',
  'Croatia': '1. High',
  'Curacao': '',
  'Cyprus': '1. High',
  'Czech Republic': '1. High',
  'Czechia': '1. High',
  'Delaware': '3. Low',
  'Denmark': '1. High',
  'Djibouti': '',
  'Dominican Republic': '2. Medium',
  'DR Congo': '',
  'Ecuador': '',
  'Egypt': '3. Low',
  'El Salvador': '',
  'Equatorial Guinea': '',
  'Eritrea': '',
  'Estonia': '1. High',
  'Eswatini': '',
  'Ethiopia': '',
  'European Union': '1. High',
  'EU': '1. High',
  'Finland': '1. High',
  'Florida': '1. High',
  'France': '1. High',
  'Gabon': '',
  'Georgia': '3. Low',
  'Germany': '1. High',
  'Ghana': '3. Low',
  'Gibraltar': '',
  'Greece': '1. High',
  'Guatemala': '',
  'Guyana': '',
  'Hawaii': '3. Low',
  'Honduras': '',
  'Hong Kong': '1. High',
  'Hungary': '1. High',
  'Iceland': '2. Medium',
  'Idaho': '3. Low',
  'Illinois': '2. Medium',
  'India': '1. High',
  'Indiana': '2. Medium',
  'Indonesia': '2. Medium',
  'Iowa': '3. Low',
  'Iran': '',
  'Iraq': '',
  'Ireland': '1. High',
  'Isle of Man': '',
  'Israel': '2. Medium',
  'Italy': '1. High',
  'Jamaica': '',
  'Japan': '1. High',
  'Jordan': '3. Low',
  'Kansas': '3. Low',
  'Kazakhstan': '3. Low',
  'Kentucky': '3. Low',
  'Kenya': '2. Medium',
  'Kosovo': '',
  'Kuwait': '3. Low',
  'Kyrgyzstan': '3. Low',
  'Laos': '3. Low',
  'Latvia': '1. High',
  'Lebanon': '3. Low',
  'Lesotho': '',
  'Liberia': '',
  'Liechtenstein': '2. Medium',
  'Lithuania': '1. High',
  'Louisiana': '3. Low',
  'Luxembourg': '1. High',
  'Macau': '',
  'Madagascar': '',
  'Maine': '3. Low',
  'Malawi': '',
  'Malaysia': '2. Medium',
  'Mali': '',
  'Malta': '1. High',
  'Manitoba': '',
  'Maryland': '2. Medium',
  'Massachusetts': '1. High',
  'Mauritius': '3. Low',
  'Mexico': '2. Medium',
  'Michigan': '2. Medium',
  'Minnesota': '2. Medium',
  'Mississippi': '3. Low',
  'Missouri': '3. Low',
  'Moldova': '3. Low',
  'Monaco': '3. Low',
  'Mongolia': '',
  'Montana': '3. Low',
  'Montenegro': '',
  'Morocco': '3. Low',
  'Mozambique': '',
  'Myanmar': '3. Low',
  'Namibia': '3. Low',
  'Nebraska': '2. Medium',
  'Nepal': '3. Low',
  'Netherlands': '1. High',
  'Nevada': '3. Low',
  'New Brunswick': '',
  'New Hampshire': '3. Low',
  'New Jersey': '1. High',
  'New Mexico': '3. Low',
  'New South Wales': '',
  'New York': '1. High',
  'New Zealand': '1. High',
  'Newfoundland and Labrador': '',
  'Nicaragua': '',
  'Niger': '',
  'Nigeria': '3. Low',
  'North Carolina': '2. Medium',
  'North Dakota': '3. Low',
  'North Korea': '',
  'North Macedonia': '2. Medium',
  'Northern Ireland': '',
  'Norway': '1. High',
  'Nova Scotia': '',
  'Ohio': '2. Medium',
  'Oklahoma': '3. Low',
  'Oman': '3. Low',
  'Ontario': '1. High',
  'Oregon': '2. Medium',
  'Pakistan': '3. Low',
  'Palau': '',
  'Panama': '2. Medium',
  'Papua New Guinea': '',
  'Paraguay': '2. Medium',
  'Pennsylvania': '1. High',
  'Peru': '1. High',
  'Philippines': '2. Medium',
  'Poland': '1. High',
  'Portugal': '1. High',
  'Prince Edward Island': '',
  'Puerto Rico': '2. Medium',
  'Qatar': '2. Medium',
  'Quebec': '1. High',
  'Queensland': '',
  'Republic of Congo': '',
  'Rhode Island': '3. Low',
  'Romania': '1. High',
  'Russia': '',
  'Rwanda': '',
  'Saint Kitts and Nevis': '',
  'Saskatchewan': '',
  'Saudi Arabia': '2. Medium',
  'Senegal': '',
  'Serbia': '2. Medium',
  'Seychelles': '',
  'Sierra Leone': '',
  'Singapore': '1. High',
  'Slovakia': '1. High',
  'Slovenia': '1. High',
  'Solomon Islands': '',
  'South Africa': '2. Medium',
  'South Australia': '',
  'South Carolina': '3. Low',
  'South Dakota': '3. Low',
  'South Korea': '1. High',
  'Korea': '1. High',
  'Spain': '1. High',
  'Sri Lanka': '3. Low',
  'Suriname': '',
  'Sweden': '1. High',
  'Switzerland': '1. High',
  'Taiwan': '',
  'Tajikistan': '3. Low',
  'Tanzania': '',
  'Tasmania': '',
  'Tennessee': '3. Low',
  'Texas': '2. Medium',
  'Thailand': '2. Medium',
  'Togo': '',
  'Trinidad and Tobago': '',
  'Tunisia': '3. Low',
  'Turkey': '2. Medium',
  'Turkmenistan': '3. Low',
  'Turks and Caicos Islands': '',
  'US Virgin Islands': '',
  'Uganda': '3. Low',
  'Ukraine': '',
  'United Arab Emirates': '2. Medium',
  'UAE': '2. Medium',
  'United Kingdom': '1. High',
  'UK': '1. High',
  'United States': '',
  'US': '',
  'Uruguay': '3. Low',
  'Utah': '3. Low',
  'Uzbekistan': '3. Low',
  'Vanuatu': '',
  'Venezuela': '',
  'Vermont': '3. Low',
  'Victoria': '',
  'Vietnam': '2. Medium',
  'Virginia': '2. Medium',
  'Washington': '3. Low',
  'West Virginia': '3. Low',
  'Western Australia': '',
  'Wisconsin': '2. Medium',
  'Wyoming': '2. Medium',
  'Zambia': '3. Low',
  'Zimbabwe': '',
  // Federal/global fallbacks
  'Federal': '1. High',
  'Global': '',
};

export const BANDING_ORDER = { '1. High': 0, '2. Medium': 1, '3. Low': 2, '': 3 };

export const BANDING_STYLE = {
  '1. High':   { bg: '#fee2e2', color: '#b91c1c', label: 'High' },
  '2. Medium': { bg: '#fef3c7', color: '#b45309', label: 'Medium' },
  '3. Low':    { bg: '#dcfce7', color: '#15803d', label: 'Low' },
  '':          { bg: '#f3f4f6', color: '#6b7280', label: 'Unrated' },
};

/**
 * Look up the FS banding for a jurisdiction string.
 * Does a case-insensitive substring match against the bandings map.
 */
export function getBanding(jurisdiction) {
  if (!jurisdiction) return '';
  const j = jurisdiction.toLowerCase();
  // Exact match first
  for (const [key, val] of Object.entries(JURISDICTION_BANDINGS)) {
    if (key.toLowerCase() === j) return val;
  }
  // Substring match
  for (const [key, val] of Object.entries(JURISDICTION_BANDINGS)) {
    if (j.includes(key.toLowerCase()) || key.toLowerCase().includes(j)) return val;
  }
  return '';
}
